/* data.js — central data for Kanji no Michi app */

const CATEGORIES = [
  { id:"verbs", jp:"動詞", en:"Verbs", desc:"Actions & motion", glyph:"動",
    words:[
      {k:"押す", h:"おす", m:"to push"},
      {k:"曲がる", h:"まがる", m:"to bend; to turn"},
      {k:"置く", h:"おく", m:"to put"},
      {k:"返す", h:"かえす", m:"to give back; to return"},
      {k:"拾う", h:"ひろう", m:"to pick up"},
      {k:"冷やす", h:"ひやす", m:"to chill; cool"},
      {k:"疲れる", h:"つかれる", m:"to get tired"},
      {k:"捨てる", h:"すてる", m:"to throw away"},
      {k:"覚える", h:"おぼえる", m:"to remember; learn"},
      {k:"洗う", h:"あらう", m:"to wash"},
      {k:"働く", h:"はたらく", m:"to work"},
      {k:"合う", h:"あう", m:"to fit; match"},
      {k:"支える", h:"ささえる", m:"to support"},
    ]},
  { id:"iadj", jp:"い形容詞", en:"i-Adjectives", desc:"Describing qualities", glyph:"形",
    words:[
      {k:"深い", h:"ふかい", m:"deep"},
      {k:"厚い", h:"あつい", m:"thick"},
      {k:"苦しい", h:"くるしい", m:"painful; difficult"},
      {k:"暑い", h:"あつい", m:"hot (weather)"},
      {k:"暗い", h:"くらい", m:"dark"},
      {k:"涼しい", h:"すずしい", m:"cool (weather)"},
    ]},
  { id:"nouns", jp:"名詞", en:"Nouns / Everyday Objects", desc:"People, places & things", glyph:"名",
    words:[
      {k:"階段", h:"かいだん", m:"stairs"},
      {k:"神", h:"かみ", m:"god; deity"},
      {k:"葉", h:"は", m:"leaf"},
      {k:"星", h:"ほし", m:"star"},
      {k:"声", h:"こえ", m:"voice"},
    ]},
  { id:"time", jp:"時間", en:"Time, Sequence & Frequency", desc:"When & how often", glyph:"時",
    words:[
      {k:"週末", h:"しゅうまつ", m:"weekend"},
      {k:"次回", h:"じかい", m:"next time; next occasion"},
    ]},
  { id:"people", jp:"人と社会", en:"People, Relationships & Society", desc:"Who & how we relate", glyph:"人",
    words:[
      {k:"相手", h:"あいて", m:"partner; companion; opponent"},
      {k:"熱心", h:"ねっしん", m:"enthusiastic; devoted"},
    ]},
  { id:"food", jp:"食と生活", en:"Food & Daily Life", desc:"The everyday routine", glyph:"食",
    words:[
      {k:"洗濯", h:"せんたく", m:"laundry"},
      {k:"食費", h:"しょくひ", m:"food expenses"},
      {k:"好き", h:"すき", m:"liked; fond of"},
    ]},
  { id:"work", jp:"学びと仕事", en:"Study, Work & Communication", desc:"School, career & talk", glyph:"学",
    words:[
      {k:"予約", h:"よやく", m:"reservation; appointment"},
      {k:"辞書", h:"じしょ", m:"dictionary"},
      {k:"面接", h:"めんせつ", m:"interview"},
      {k:"倍率", h:"ばいりつ", m:"magnification; ratio"},
      {k:"取材", h:"しゅざい", m:"interview; coverage; reporting"},
      {k:"退学", h:"たいがく", m:"leaving school; withdrawal from school"},
      {k:"化学", h:"かがく", m:"chemistry"},
      {k:"役に立つ", h:"やくにたつ", m:"to be useful"},
      {k:"文化", h:"ぶんか", m:"culture"},
      {k:"説明", h:"せつめい", m:"explanation"},
      {k:"求人", h:"きゅうじん", m:"recruiting; job opening"},
      {k:"市役所", h:"しやくしょ", m:"city hall"},
    ]},
  { id:"abstract", jp:"抽象概念", en:"Abstract Concepts", desc:"Ideas & stances", glyph:"念",
    words:[
      {k:"挑戦", h:"ちょうせん", m:"challenge"},
      {k:"活動", h:"かつどう", m:"activity"},
      {k:"借金", h:"しゃっきん", m:"debt"},
      {k:"種類", h:"しゅるい", m:"kind; type; category"},
      {k:"賛成", h:"さんせい", m:"agreement; approval; being in favor"},
      {k:"反対", h:"はんたい", m:"opposition; being against"},
      {k:"建設", h:"けんせつ", m:"construction"},
      {k:"都合", h:"つごう", m:"circumstances; convenience"},
      {k:"区別", h:"くべつ", m:"distinction; classification"},
      {k:"失敗", h:"しっぱい", m:"failure"},
      {k:"原因", h:"げんいん", m:"cause; reason"},
      {k:"理由", h:"りゆう", m:"reason"},
      {k:"国際", h:"こくさい", m:"international"},
      {k:"祝福", h:"しゅくふく", m:"blessing; congratulations"},
    ]},
];

const byId = id => CATEGORIES.find(c => c.id === id);
