/* data.js — central data for Kanji no Michi app
 *
 * Source: Nihongo So-matome N3 Kanji — daily study plan
 * (Nihongo_so-matome_N3_Kanji_daily.xlsx, "All Cards" sheet).
 *
 * The course is split into 6 weeks of 7 days. Each day is one study set;
 * its `id` doubles as the cat_id used by the local SQL database, so ids
 * must stay stable across regenerations.
 */

const WEEK_NUMERALS = ["一","二","三","四","五","六"];

const CATEGORIES = [
  { id:"w1d1", week:1, day:1, route:"w1/d1", jp:"一日目", en:"Day 1", glyph:"日",
    words:[
      {k:"駐車", h:"ちゅうしゃ", m:"park"},
      {k:"駐車場", h:"ちゅうしゃじょう", m:"a parking lot"},
      {k:"無休", h:"むきゅう", m:"working w/o holiday"},
      {k:"無理な", h:"むりな", m:"unreasonable"},
      {k:"無料", h:"むりょう", m:"free of charge"},
      {k:"無い", h:"ない", m:"doesn't exist, don't have, gone"},
      {k:"満車", h:"まんしゃ", m:"full (of cars)"},
      {k:"不満", h:"ふまん", m:"dissatisfied, discontented"},
      {k:"満員", h:"まんいん", m:"full (of people)"},
      {k:"方向", h:"ほうこう", m:"direction"},
      {k:"向かう", h:"むかう", m:"to go forward/to face/to turn (toward)"},
      {k:"向こう", h:"むこう", m:"over there/beyond, across, on other side"},
      {k:"〜向き", h:"〜むき", m:"be suitable for ~"},
      {k:"禁止", h:"きんし", m:"prohibition"},
      {k:"関心", h:"かんしん", m:"interest"},
      {k:"関する", h:"かんする", m:"to be related/connected to, to be concerned with"},
      {k:"関係", h:"かんけい", m:"relation, connection"},
      {k:"係", h:"かかり", m:"person in charge"},
      {k:"無断", h:"むだん", m:"without permission"},
      {k:"断る", h:"ことわる", m:"to refuse"},
      {k:"断水", h:"だんすい", m:"suspension of water supply"},
    ]},
  { id:"w1d2", week:1, day:2, route:"w1/d2", jp:"二日目", en:"Day 2", glyph:"日",
    words:[
      {k:"横断", h:"おうだん", m:"a crossing"},
      {k:"横", h:"よこ", m:"side"},
      {k:"横断歩道", h:"おうだんほどう", m:"a pedestrian crossing"},
      {k:"押す", h:"おす", m:"to push/press"},
      {k:"押し入れ", h:"おしいれ", m:"a closet"},
      {k:"押さえる", h:"おさえる", m:"to hold down"},
      {k:"押しボタン式", h:"おしボタンしき", m:"a push-button..."},
      {k:"数式", h:"すうしき", m:"a numerical formula"},
      {k:"入学式", h:"にゅうがくしき", m:"a ceremony to begin school"},
      {k:"送信", h:"そうしん", m:"transmission (of message)"},
      {k:"自信", h:"じしん", m:"confidence"},
      {k:"信じる", h:"しんじる", m:"to believe"},
      {k:"信用", h:"しんよう", m:"trust"},
      {k:"信号", h:"しんごう", m:"a signal/ a traffic light"},
      {k:"〜号車", h:"〜ごうしゃ", m:"carriage number ~"},
      {k:"性格(な）", h:"せいかく（な）", m:"correct, accurate"},
      {k:"確かめる", h:"たしかめる", m:"to confirm/verify"},
      {k:"確か(な）", h:"たしか（な）", m:"certain"},
      {k:"確認", h:"かくにん", m:"confirmation"},
      {k:"認める", h:"みとめる", m:"to admit, to approve"},
      {k:"飛行場", h:"ひこうじょう", m:"an airport"},
    ]},
  { id:"w1d3", week:1, day:3, route:"w1/d3", jp:"三日目", en:"Day 3", glyph:"日",
    words:[
      {k:"飛ぶ", h:"とぶ", m:"to fly"},
      {k:"非常", h:"ひじょう", m:"emergency"},
      {k:"非常口", h:"ひじょうぐち", m:"emergency exit"},
      {k:"非常に", h:"ひじょうに", m:"extremely"},
      {k:"日常（の）", h:"にちじょう（の）", m:"usual, everyday"},
      {k:"正常（な）", h:"せいじょう（な）", m:"normal"},
      {k:"〜階", h:"〜かい", m:"floor~"},
      {k:"階段", h:"かいだん", m:"stairs"},
      {k:"箱", h:"はこ", m:"a box"},
      {k:"ゴミ箱", h:"ごみばこ", m:"a trash box"},
      {k:"危険（な）", h:"きけん（な）", m:"danger"},
      {k:"危ない", h:"あぶない", m:"dangerous"},
      {k:"捨てる", h:"すてる", m:"to throw away"},
      {k:"線", h:"せん", m:"a line"},
      {k:"〜番線", h:"〜ばんせん", m:"line (platform) number ~"},
      {k:"全面", h:"ぜんめん", m:"whole"},
      {k:"画面", h:"がめん", m:"a screen"},
      {k:"〜方面", h:"〜ほうめん", m:"~area, district, quarter, region, direction"},
      {k:"普通（の）", h:"ふつう（の）", m:"ordinary"},
      {k:"各駅", h:"かくえき", m:"every station"},
      {k:"各自", h:"かくじ", m:"respective / each person"},
    ]},
  { id:"w1d4", week:1, day:4, route:"w1/d4", jp:"四日目", en:"Day 4", glyph:"日",
    words:[
      {k:"各国", h:"かっこく", m:"each country"},
      {k:"目次", h:"もくじ", m:"contents"},
      {k:"次", h:"つぎ", m:"next"},
      {k:"次回", h:"じかい", m:"the next time"},
      {k:"快速", h:"かいそく", m:"high speed, fast"},
      {k:"高速道路", h:"こうそくどうろ", m:"a highway"},
      {k:"速度", h:"そくど", m:"speed"},
      {k:"速い", h:"はやい", m:"fast"},
      {k:"通過", h:"つうか", m:"passage, transit"},
      {k:"過ぎる", h:"すぎる", m:"to pass"},
      {k:"過去", h:"かこ", m:"past"},
      {k:"地下鉄", h:"ちかてつ", m:"a subway"},
      {k:"鉄", h:"てつ", m:"steel"},
      {k:"鉄道", h:"てつどう", m:"a railway"},
      {k:"指定", h:"してい", m:"specify, designate"},
      {k:"指定席", h:"していせき", m:"a reserved seat"},
      {k:"指", h:"ゆび", m:"a finger"},
      {k:"指輪", h:"ゆびわ", m:"a ring"},
      {k:"定休日", h:"ていきゅうび", m:"a set/regular holiday"},
      {k:"安定", h:"あんてい", m:"stable"},
      {k:"席", h:"せき", m:"a seat"},
    ]},
  { id:"w1d5", week:1, day:5, route:"w1/d5", jp:"五日目", en:"Day 5", glyph:"日",
    words:[
      {k:"出席", h:"しゅっせき", m:"attendance, presence"},
      {k:"欠席", h:"けっせき", m:"absence"},
      {k:"自由（な）", h:"じゆう（な）", m:"free"},
      {k:"理由", h:"りゆう", m:"reason"},
      {k:"自由席", h:"じゆうせき", m:"a non-reserved seat"},
      {k:"番号", h:"ばんごう", m:"a number"},
      {k:"〜番線", h:"〜ばんせん", m:"line (platform) number ~"},
      {k:"〜番", h:"〜ばん", m:"no~"},
      {k:"窓", h:"まど", m:"a window"},
      {k:"窓口", h:"まどぐち", m:"a teller's window"},
      {k:"両側", h:"りょうがわ", m:"both sides"},
      {k:"窓側", h:"まどがわ", m:"a window seat"},
      {k:"右側", h:"みぎがわ", m:"the right side"},
      {k:"通路", h:"つうろ", m:"an isle"},
      {k:"線路", h:"せんろ", m:"a railway"},
      {k:"道路", h:"どうろ", m:"a road"},
      {k:"停車", h:"ていしゃ", m:"stopped vehicle"},
      {k:"バス停", h:"バスてい", m:"a bus stop"},
      {k:"整理", h:"せいり", m:"tidy"},
      {k:"整理券", h:"せいりけん", m:"numbered ticket (issued at cinemas,etc)"},
    ]},
  { id:"w1d6", week:1, day:6, route:"w1/d6", jp:"六日目", en:"Day 6", glyph:"日",
    words:[
      {k:"駐車券", h:"ちゅうしゃけん", m:"a parking ticket"},
      {k:"回数券", h:"かいすうけん", m:"(book of) commuter ticket(s)"},
      {k:"乗車券", h:"じょうしゃけん", m:"a (boarding) ticket"},
      {k:"現金", h:"げんきん", m:"cash"},
      {k:"現れる", h:"あらわれる", m:"to appear"},
      {k:"表現", h:"ひょうげん", m:"expression"},
      {k:"両親", h:"りょうしん", m:"parents"},
      {k:"〜両", h:"〜りょう", m:"...cars on a train"},
      {k:"取り替える", h:"とりかえる", m:"to exchange"},
      {k:"着替える", h:"きがえる", m:"to change clothes"},
      {k:"両替", h:"りょうがえ", m:"exchange"},
      {k:"優先席", h:"ゆうせんせき", m:"a priority seat"},
      {k:"優しい", h:"やさしい", m:"kind"},
      {k:"女優", h:"じょゆう", m:"an actress"},
      {k:"座席", h:"ざせき", m:"a seat"},
      {k:"座る", h:"すわる", m:"to sit"},
      {k:"正座", h:"せいざ", m:"sit on floor in japanese style"},
      {k:"降車口", h:"こうしゃぐち", m:"exit (for getting off)"},
      {k:"降りる", h:"おりる", m:"to get off"},
      {k:"以降", h:"いこう", m:"after....."},
    ]},
  { id:"w1d7", week:1, day:7, route:"w1/d7", jp:"七日目", en:"Day 7", glyph:"日",
    words:[
      {k:"降る", h:"ふる", m:"to fall"},
      {k:"未定", h:"みてい", m:"undecided/indefinite"},
      {k:"〜未満", h:"〜みまん", m:"less than..."},
      {k:"未来", h:"みらい", m:"future"},
      {k:"週末", h:"しゅうまつ", m:"the weekend"},
      {k:"年末", h:"ねんまつ", m:"the end of the year"},
      {k:"月末", h:"げつまつ", m:"the end of the month"},
      {k:"若い", h:"わかい", m:"young"},
      {k:"晩", h:"ばん", m:"night"},
      {k:"晩ご飯", h:"ばんごはん", m:"dinner"},
      {k:"今晩", h:"こんばん", m:"tonight"},
      {k:"毎晩", h:"まいばん", m:"every night"},
      {k:"〜島", h:"〜とう", m:"~ island"},
      {k:"島", h:"しま", m:"an island"},
      {k:"皿", h:"さら", m:"a plate"},
      {k:"灰皿", h:"はいざら", m:"an ashtray"},
      {k:"出血", h:"しゅっけつ", m:"bleeding; loss of blood"},
      {k:"血", h:"ち", m:"blood"},
      {k:"救助", h:"きゅうじょ", m:"rescue, help"},
      {k:"助ける", h:"たすける", m:"to help -"},
    ]},
  { id:"w2d1", week:2, day:1, route:"w2/d1", jp:"一日目", en:"Day 1", glyph:"日",
    words:[
      {k:"準備", h:"じゅんび", m:"preparation"},
      {k:"備える", h:"そなえる", m:"to prepare"},
      {k:"営業", h:"えいぎょう", m:"business"},
      {k:"開閉", h:"かいへい", m:"open and shut"},
      {k:"閉まる", h:"しまる", m:"to close/shut"},
      {k:"閉める", h:"しめる", m:"to close/shut"},
      {k:"案内", h:"あんない", m:"information"},
      {k:"案", h:"あん", m:"a suggestion, proposal, plan"},
      {k:"家内", h:"かない", m:"wife"},
      {k:"内側", h:"うちがわ", m:"inside"},
      {k:"以内", h:"いない", m:"within..."},
      {k:"国内", h:"こくない", m:"domestic"},
      {k:"予定", h:"よてい", m:"a plan/ schedule"},
      {k:"予習", h:"よしゅう", m:"preparation (pre-study)"},
      {k:"予約", h:"よやく", m:"an appointment/reservation"},
      {k:"約〜", h:"やく〜", m:"approximately"},
      {k:"禁煙", h:"きんえん", m:"no smoking"},
      {k:"煙", h:"けむり", m:"smoke"},
      {k:"本当", h:"ほんとう", m:"the truth, really"},
      {k:"当たる", h:"あたる", m:"to hit, to win"},
    ]},
  { id:"w2d2", week:2, day:2, route:"w2/d2", jp:"二日目", en:"Day 2", glyph:"日",
    words:[
      {k:"当。。。。", h:"とう。。。", m:"this....."},
      {k:"当たり前", h:"あたり", m:"natural, not surprising"},
      {k:"全部", h:"ぜんぶ", m:"all, whole"},
      {k:"全席", h:"ぜんせき", m:"all seats"},
      {k:"安全（な）", h:"あんぜん（な）", m:"safe"},
      {k:"客", h:"きゃく", m:"a customer"},
      {k:"お客様", h:"おきゃくさま", m:"a customer"},
      {k:"様子", h:"ようす", m:"appearance, situation"},
      {k:"〜様", h:"〜さま", m:"Mr...., Ms....,Mrs...."},
      {k:"理解", h:"りかい", m:"understand"},
      {k:"解説", h:"かいせつ", m:"an explanation"},
      {k:"解答", h:"かいとう", m:"an answer"},
      {k:"分解", h:"ぶんかい", m:"taking apart"},
      {k:"協力", h:"きょうりょく", m:"cooperation"},
      {k:"願う", h:"ねがう", m:"a wish"},
      {k:"観光", h:"かんこう", m:"sightseeing"},
      {k:"観客", h:"かんきゃく", m:"spectator, audience"},
      {k:"動物園", h:"どうぶつえん", m:"a zoo"},
      {k:"空港", h:"くうこう", m:"an airport"},
      {k:"港", h:"みなと", m:"a port"},
    ]},
  { id:"w2d3", week:2, day:3, route:"w2/d3", jp:"三日目", en:"Day 3", glyph:"日",
    words:[
      {k:"〜港", h:"〜こう", m:"~port"},
      {k:"遊園地", h:"ゆうえんち", m:"an amusement park"},
      {k:"遊ぶ", h:"あそぶ", m:"to play"},
      {k:"美術館", h:"びじゅつかん", m:"a museum"},
      {k:"美しい", h:"うつくしい", m:"beautiful"},
      {k:"美人", h:"びじん", m:"a beautiful woman"},
      {k:"美術", h:"びじゅつ", m:"(fine) art"},
      {k:"手術", h:"しゅじゅつ", m:"surgery, operation"},
      {k:"技術", h:"ぎじゅつ", m:"technique, technology"},
      {k:"神社", h:"じんじゃ", m:"a shrine"},
      {k:"神様", h:"かみさま", m:"a god"},
      {k:"神経質（な）", h:"しんけいしつ（な）", m:"nervous"},
      {k:"〜寺", h:"〜じ", m:"~temple"},
      {k:"お寺", h:"おてら", m:"a temple"},
      {k:"市役所", h:"しやくしょ", m:"the city office"},
      {k:"役員", h:"やくいん", m:"an officer/member"},
      {k:"役に立つ", h:"やくにたつ", m:"useful"},
      {k:"郵便", h:"ゆうびん", m:"mail"},
      {k:"郵便局", h:"ゆうびんきょく", m:"a post office"},
    ]},
  { id:"w2d4", week:2, day:4, route:"w2/d4", jp:"四日目", en:"Day 4", glyph:"日",
    words:[
      {k:"薬局", h:"やっきょく", m:"a drug store, pharmacist"},
      {k:"交番", h:"こうばん", m:"a police box"},
      {k:"交換", h:"こうかん", m:"exchange"},
      {k:"交通", h:"こうつう", m:"transport"},
      {k:"差", h:"さ", m:"difference"},
      {k:"差し出す", h:"さしだす", m:"to hand in"},
      {k:"差出人", h:"さしだしにん", m:"a sender"},
      {k:"交差点", h:"こうさてん", m:"an intersection"},
      {k:"〜点", h:"〜てん", m:"....points"},
      {k:"点数", h:"てんすう", m:"score/points"},
      {k:"歩道橋", h:"ほどうきょう", m:"a foot bridge"},
      {k:"橋", h:"はし", m:"a bridge"},
      {k:"公園", h:"こうえん", m:"a park"},
      {k:"受信", h:"じゅしん", m:"receiving"},
      {k:"受ける", h:"うける", m:"to receive"},
      {k:"受験", h:"じゅけん", m:"an entrance examination"},
      {k:"付ける", h:"つける", m:"to put on"},
      {k:"受付", h:"うけつけ", m:"a reception"},
      {k:"片付ける", h:"かたづける", m:"to tidy up"},
    ]},
  { id:"w2d5", week:2, day:5, route:"w2/d5", jp:"五日目", en:"Day 5", glyph:"日",
    words:[
      {k:"付く", h:"つく", m:"to stick to"},
      {k:"科学", h:"かがく", m:"science"},
      {k:"内科", h:"ないか", m:"internal medicine"},
      {k:"外科", h:"げか", m:"surgery department"},
      {k:"教科書", h:"きょうかしょ", m:"a textbook"},
      {k:"耳鼻科", h:"じびか", m:"ears and nose department"},
      {k:"鼻", h:"はな", m:"a nose"},
      {k:"婦人", h:"ふじん", m:"a woman"},
      {k:"主婦", h:"しゅふ", m:"a housewife"},
      {k:"産婦人科", h:"さんふじんか", m:"obstetrics and gynaecology department"},
      {k:"形式", h:"けいしき", m:"form/ type"},
      {k:"整形外科", h:"せいけいげか", m:"orthopedics department"},
      {k:"人形", h:"にんぎょう", m:"a doll, puppet"},
      {k:"図形", h:"ずけい", m:"a diagram, a figure"},
      {k:"形", h:"かたち", m:"shape, form"},
      {k:"骨折", h:"こっせつ", m:"a bone fracture"},
      {k:"骨", h:"ほね", m:"a bone"},
      {k:"右折", h:"うせつ", m:"a right turn"},
      {k:"折る", h:"おる", m:"to break into 2, to snap, to fold something"},
    ]},
  { id:"w2d6", week:2, day:6, route:"w2/d6", jp:"六日目", en:"Day 6", glyph:"日",
    words:[
      {k:"折れる", h:"おれる", m:"to break, to be broken, to snap"},
      {k:"左折", h:"させつ", m:"a left turn"},
      {k:"折り紙", h:"おりがみ", m:"japanese art of folding paper"},
      {k:"困る", h:"こまる", m:"to be in trouble"},
      {k:"消防", h:"しょうぼう", m:"fire fighting"},
      {k:"消す", h:"けす", m:"to extinguish"},
      {k:"消える", h:"きえる", m:"to be extinguished, to be disappeared"},
      {k:"消しゴム", h:"けしごむ", m:"an eraser"},
      {k:"予防", h:"よぼう", m:"precaution, prevention"},
      {k:"防ぐ", h:"ふせぐ", m:"to prevent"},
      {k:"救急車", h:"きゅうきゅうしゃ", m:"an ambulance"},
      {k:"救う", h:"すくう", m:"to save"},
      {k:"警官", h:"けいかん", m:"a police officer"},
      {k:"警察", h:"けいさつ", m:"police"},
      {k:"警察署", h:"けいさつしょ", m:"a police station"},
      {k:"事故", h:"じこ", m:"an accident"},
      {k:"故。。。", h:"こ。。。。", m:"the late Mr....."},
      {k:"故障", h:"こしょう", m:"break down, failure"},
      {k:"伝言", h:"でんごん", m:"a message"},
    ]},
  { id:"w2d7", week:2, day:7, route:"w2/d7", jp:"七日目", en:"Day 7", glyph:"日",
    words:[
      {k:"伝える", h:"つたえる", m:"to convey, to communicate"},
      {k:"手伝う", h:"てつだう", m:"to help"},
      {k:"黄色", h:"きいろ", m:"yellow"},
      {k:"黄色い", h:"きいろい", m:"yellow"},
      {k:"絵画", h:"かいが", m:"a painting"},
      {k:"絵", h:"え", m:"a picture"},
      {k:"絵本", h:"えほん", m:"a picture book"},
      {k:"〜組", h:"〜くみ", m:"pairs"},
      {k:"組む", h:"くむ", m:"to team up"},
      {k:"番組", h:"ばんぐみ", m:"a (TV) program"},
      {k:"組み立てる", h:"くみたてる", m:"to put together"},
      {k:"約束", h:"やくそく", m:"a promise/ appointment"},
      {k:"〜束", h:"〜たば", m:"a bundle, a bunch"},
      {k:"花束", h:"はなたば", m:"bunch of flowers"},
      {k:"授業", h:"じゅぎょう", m:"a class"},
      {k:"教授", h:"きょうじゅ", m:"a professor"},
      {k:"渡る", h:"わたる", m:"to cross over"},
      {k:"渡す", h:"わたす", m:"to hand over"},
      {k:"昔", h:"むかし", m:"long ago, past"},
    ]},
  { id:"w3d1", week:3, day:1, route:"w3/d1", jp:"一日目", en:"Day 1", glyph:"日",
    words:[
      {k:"必要（な）", h:"ひつよう（な）", m:"necessary"},
      {k:"要る", h:"いる", m:"to need"},
      {k:"重要（な）", h:"じゅうよう（な）", m:"important"},
      {k:"冷房", h:"れいぼう", m:"air-conditioning"},
      {k:"冷やす", h:"ひやす", m:"to cool"},
      {k:"冷める", h:"さめる", m:"to cool down"},
      {k:"冷たい", h:"つめたい", m:"cold"},
      {k:"冷える", h:"ひえる", m:"to become cold"},
      {k:"冷ます", h:"さます", m:"to cool something"},
      {k:"冷蔵庫", h:"れいぞうこ", m:"a refrigerator"},
      {k:"冷凍庫", h:"れいとうこ", m:"a freezer"},
      {k:"凍る", h:"こおる", m:"to freeze"},
      {k:"金庫", h:"きんこ", m:"a safe"},
      {k:"車庫", h:"しゃこ", m:"a garage"},
      {k:"召し上がる", h:"めしあがる", m:"to eat (polite form)"},
      {k:"保存する", h:"ほぞんする", m:"to preserve"},
      {k:"ご存じです", h:"ごぞんじです", m:"to know (humble form)"},
      {k:"存じません", h:"ぞんじません", m:"I do not know"},
      {k:"必ず", h:"かならず", m:"always, certainly, without failure"},
      {k:"必死（に）", h:"ひっし（に）", m:"desperately"},
      {k:"費用", h:"ひよう", m:"an expense, cost"},
      {k:"旅費", h:"りょひ", m:"travelling expense"},
    ]},
  { id:"w3d2", week:3, day:2, route:"w3/d2", jp:"二日目", en:"Day 2", glyph:"日",
    words:[
      {k:"消費者", h:"しょうひしゃ", m:"consumers"},
      {k:"会費", h:"かいひ", m:"a membership fee"},
      {k:"期間", h:"きかん", m:"a period of time"},
      {k:"長期", h:"ちょうき", m:"a long period"},
      {k:"定期券", h:"ていきけん", m:"a commuter pass"},
      {k:"短期", h:"たんき", m:"a short period"},
      {k:"期限", h:"きげん", m:"a time limit"},
      {k:"限る", h:"かぎる", m:"to limit, to restrict"},
      {k:"限度", h:"げんど", m:"a limit"},
      {k:"限定", h:"げんてい", m:"limitation"},
      {k:"〜製", h:"〜せい", m:"made in/of ~"},
      {k:"製品", h:"せいひん", m:"a product"},
      {k:"製造", h:"せいぞう", m:"manufacture"},
      {k:"造る", h:"つくる", m:"to make"},
      {k:"賞", h:"しょう", m:"a prize"},
      {k:"賞金", h:"しょうきん", m:"prize money"},
      {k:"賞味期限", h:"しょうみきげん", m:"Best before"},
      {k:"賞品", h:"しょうひん", m:"a prize"},
      {k:"方法", h:"ほうほう", m:"a method/ way"},
      {k:"文法", h:"ぶんぽう", m:"grammar"},
      {k:"温度", h:"おんど", m:"temperature"},
      {k:"温かい", h:"あたたかい", m:"warm"},
    ]},
  { id:"w3d3", week:3, day:3, route:"w3/d3", jp:"三日目", en:"Day 3", glyph:"日",
    words:[
      {k:"気温", h:"きおん", m:"temperature"},
      {k:"常温", h:"じょうおん", m:"normal temperature"},
      {k:"販売", h:"はんばい", m:"sell"},
      {k:"自動販売機", h:"じどうはんばいき", m:"a vending machine"},
      {k:"飛行機", h:"ひこうき", m:"an airplane"},
      {k:"機会", h:"きかい", m:"an opportunity"},
      {k:"機械", h:"きかい", m:"a machine"},
      {k:"増加", h:"ぞうか", m:"an increase"},
      {k:"増える", h:"ふえる", m:"to increase"},
      {k:"増やす", h:"ふやす", m:"to increase, to add"},
      {k:"減少", h:"げんしょう", m:"a decrease"},
      {k:"減る", h:"へる", m:"to decrease, to reduce"},
      {k:"減らす", h:"へらす", m:"to decrease"},
      {k:"量", h:"りょう", m:"quantity"},
      {k:"増量", h:"ぞうりょう", m:"increase the amount"},
      {k:"数量", h:"すうりょう", m:"amount"},
      {k:"減量", h:"げんりょう", m:"a loss in quantity (weight)"},
      {k:"氷", h:"こおり", m:"ice"},
      {k:"返事", h:"へんじ", m:"a reply"},
      {k:"返す", h:"かえす", m:"to return (something)"},
      {k:"返却", h:"へんきゃく", m:"return"},
      {k:"（お）湯", h:"おゆ", m:"hot water"},
    ]},
  { id:"w3d4", week:3, day:4, route:"w3/d4", jp:"四日目", en:"Day 4", glyph:"日",
    words:[
      {k:"材料", h:"ざいりょう", m:"ingredients, materials"},
      {k:"教材", h:"きょうざい", m:"teaching material"},
      {k:"卵", h:"たまご", m:"an egg"},
      {k:"卵焼き", h:"たまごやき", m:"a japanese omlet"},
      {k:"牛乳", h:"ぎゅうにゅう", m:"milk"},
      {k:"粉", h:"こな", m:"powder, flour"},
      {k:"小麦粉", h:"こむぎこ", m:"wheat flour"},
      {k:"袋", h:"ふくろ", m:"a bag"},
      {k:"ゴミ袋", h:"ごみふくろ", m:"a garbage bag"},
      {k:"足袋", h:"たび", m:"traditional japs socks worn with kimono"},
      {k:"紙袋", h:"かみぶくろ", m:"a paper bag"},
      {k:"手袋", h:"てぶくろ", m:"gloves"},
      {k:"混雑", h:"こんざつ", m:"congestion"},
      {k:"混ぜる", h:"まぜる", m:"to be mixed"},
      {k:"焼く", h:"やく", m:"to roast, to grill"},
      {k:"焼ける", h:"やける", m:"to be burnt/baked"},
      {k:"表", h:"ひょう", m:"a table (in written documents)"},
      {k:"発表", h:"はっぴょう", m:"an announcement"},
      {k:"表", h:"おもて", m:"a surface, face"},
      {k:"表面", h:"ひょうめん", m:"a surface"},
      {k:"代表", h:"だいひょう", m:"a representative"},
      {k:"表す", h:"あらわす", m:"to show, to express"},
    ]},
  { id:"w3d5", week:3, day:5, route:"w3/d5", jp:"五日目", en:"Day 5", glyph:"日",
    words:[
      {k:"裏", h:"うら", m:"reverse, back"},
      {k:"裏返す", h:"うらがえす", m:"to turnover"},
      {k:"留学", h:"りゅうがく", m:"study abroad"},
      {k:"保留", h:"ほりゅう", m:"reservation, suspension"},
      {k:"留守番", h:"るすばん", m:"stay at home"},
      {k:"書留", h:"かきとめ", m:"registration (registered mail)"},
      {k:"守備", h:"しゅび", m:"defence"},
      {k:"守る", h:"まもる", m:"to protect"},
      {k:"留守", h:"るす", m:"absence"},
      {k:"濃い", h:"こい", m:"concentrate, dark (colour)"},
      {k:"薄い", h:"うすい", m:"thin (material), light (colour), weak (drink)"},
      {k:"部分", h:"ぶぶん", m:"part"},
      {k:"部長", h:"ぶちょう", m:"department head/ manager"},
      {k:"学部", h:"がくぶ", m:"faculty"},
      {k:"部屋", h:"へや", m:"a room"},
      {k:"数字", h:"すうじ", m:"number"},
      {k:"数", h:"かず", m:"a number"},
      {k:"数学", h:"すうがく", m:"mathematics"},
      {k:"数える", h:"かぞえる", m:"to count"},
      {k:"件名", h:"けんめい", m:"subject"},
      {k:"用件", h:"ようけん", m:"a business/matter"},
    ]},
  { id:"w3d6", week:3, day:6, route:"w3/d6", jp:"六日目", en:"Day 6", glyph:"日",
    words:[
      {k:"事件", h:"じけん", m:"an incident"},
      {k:"再入国", h:"さいにゅうこく", m:"re-enter a country"},
      {k:"再生", h:"さいせい", m:"regenerate, recycle"},
      {k:"再ダイヤル", h:"さいだいやる", m:"redial"},
      {k:"再来週", h:"さらいしゅう", m:"the week after next"},
      {k:"接続", h:"せつぞく", m:"connect"},
      {k:"面接", h:"めんせつ", m:"interview"},
      {k:"続く", h:"つづく", m:"to continue"},
      {k:"続ける", h:"つづける", m:"to continue"},
      {k:"表示", h:"ひょうじ", m:"indication, expression"},
      {k:"示す", h:"しめす", m:"to show, to point out"},
      {k:"指示", h:"しじ", m:"a direction, instruction"},
      {k:"戻る", h:"もどる", m:"to return"},
      {k:"戻す", h:"もどす", m:"to return, to put back"},
      {k:"完了", h:"かんりょう", m:"completion"},
      {k:"完全（な）", h:"かんぜん（な）", m:"perfect, complete"},
      {k:"了解", h:"りょうかい", m:"understand, agree"},
      {k:"終了", h:"しゅうりょう", m:"end, expiration"},
      {k:"登録", h:"とうろく", m:"registration"},
      {k:"登る", h:"のぼる", m:"to climb"},
      {k:"登山", h:"とざん", m:"mountain climbing"},
    ]},
  { id:"w3d7", week:3, day:7, route:"w3/d7", jp:"七日目", en:"Day 7", glyph:"日",
    words:[
      {k:"記録", h:"きろく", m:"a record"},
      {k:"録音", h:"ろくおん", m:"record (sound)"},
      {k:"録画", h:"ろくが", m:"record (video)"},
      {k:"教育", h:"きょういく", m:"education"},
      {k:"育てる", h:"そだてる", m:"to raise, to bring up"},
      {k:"育つ", h:"そだつ", m:"to grow"},
      {k:"種類", h:"しゅるい", m:"type, kind"},
      {k:"種", h:"たね", m:"a seed"},
      {k:"書類", h:"しょるい", m:"a document"},
      {k:"分類", h:"ぶんるい", m:"classification"},
      {k:"人類", h:"じんるい", m:"the human race"},
      {k:"教師", h:"きょうし", m:"a teacher"},
      {k:"看護師", h:"かんごし", m:"a nurse"},
      {k:"医師", h:"いし", m:"a doctor"},
      {k:"夫妻", h:"ふさい", m:"husband and wife"},
      {k:"妻", h:"つま", m:"wife"},
      {k:"馬", h:"うま", m:"a horse"},
      {k:"乗馬", h:"じょうば", m:"horse riding"},
      {k:"石けん", h:"せっけん", m:"soap"},
      {k:"石", h:"いし", m:"stone"},
      {k:"石油", h:"せきゆ", m:"oil (petroleum)"},
    ]},
  { id:"w4d1", week:4, day:1, route:"w4/d1", jp:"一日目", en:"Day 1", glyph:"日",
    words:[
      {k:"砂糖", h:"さとう", m:"sugar"},
      {k:"砂", h:"すな", m:"sand"},
      {k:"食塩", h:"しょくえん", m:"table salt"},
      {k:"塩", h:"しお", m:"salt"},
      {k:"しょう油", h:"しょうゆ", m:"soy sauce"},
      {k:"灯油", h:"とうゆ", m:"kerosene"},
      {k:"石油", h:"せきゆ", m:"oil (petroleum)"},
      {k:"油", h:"あぶら", m:"oil"},
      {k:"緑茶", h:"りょくちゃ", m:"green tea"},
      {k:"緑（色）", h:"みどり（いろ）", m:"green"},
      {k:"紅茶", h:"こうちゃ", m:"tea"},
      {k:"口紅", h:"くちべに", m:"lipstick"},
      {k:"〜冊", h:"〜さつ", m:"counter for books"},
      {k:"冊数", h:"さっすう", m:"number of copies"},
      {k:"〜個", h:"〜こ", m:"counter of general objects"},
      {k:"個人", h:"こじん", m:"individual (person)"},
      {k:"個数", h:"こすう", m:"number of items"},
      {k:"団体", h:"だんたい", m:"a group"},
      {k:"〜枚", h:"〜まい", m:"counter for flat objects"},
      {k:"枚数", h:"まいすう", m:"number of sheets/copies"},
      {k:"広告", h:"こうこく", m:"an advertisment"},
    ]},
  { id:"w4d2", week:4, day:2, route:"w4/d2", jp:"二日目", en:"Day 2", glyph:"日",
    words:[
      {k:"便利（な）", h:"べんりな", m:"convenient"},
      {k:"割る", h:"わる", m:"to break"},
      {k:"割れる", h:"われる", m:"to crack/cleave"},
      {k:"割合", h:"わりあい", m:"a ratio, a percentage"},
      {k:"割引", h:"わりびき", m:"a discount"},
      {k:"〜倍", h:"〜ばい", m:"~times (quantity - eg. Twice as many)"},
      {k:"値段", h:"ねだん", m:"a price"},
      {k:"値上げ", h:"ねあげ", m:"a price increase"},
      {k:"値下げ", h:"ねさげ", m:"a price reduction"},
      {k:"商品", h:"しょうひん", m:"goods"},
      {k:"商店", h:"しょうてん", m:"a shop"},
      {k:"支店", h:"してん", m:"a branch"},
      {k:"支社", h:"ししゃ", m:"a branch office"},
      {k:"本店", h:"ほんてん", m:"main branch of a store"},
      {k:"本社", h:"ほんしゃ", m:"head office"},
      {k:"払う", h:"はらう", m:"to pay"},
      {k:"支払い", h:"しはらい", m:"a payment"},
      {k:"米国", h:"べいこく", m:"the United States of America"},
      {k:"米", h:"こめ", m:"rice"},
      {k:"高級", h:"こうきゅう", m:"high class/grade"},
      {k:"上級", h:"じょうきゅう", m:"advanced level"},
    ]},
  { id:"w4d3", week:4, day:3, route:"w4/d3", jp:"三日目", en:"Day 3", glyph:"日",
    words:[
      {k:"中級", h:"ちゅうきゅう", m:"intermediate level"},
      {k:"残業", h:"ざんぎょう", m:"overtime work"},
      {k:"残る", h:"のこる", m:"to remain"},
      {k:"残り", h:"のこり", m:"the remainder"},
      {k:"残す", h:"のこす", m:"to leave, to leave behind"},
      {k:"大型", h:"おおがた", m:"large, jumbo"},
      {k:"新型", h:"しんがた", m:"new model"},
      {k:"小型", h:"こがた", m:"small-sized"},
      {k:"消費税", h:"しょうひぜい", m:"consumption tax"},
      {k:"税金", h:"ぜいきん", m:"a tax"},
      {k:"込む", h:"こむ", m:"to congest/crowd"},
      {k:"振り込む", h:"ふりこむ", m:"to transfer money to someone's account"},
      {k:"税込", h:"ぜいこみ", m:"tax included"},
      {k:"価格", h:"かかく", m:"a price"},
      {k:"定価", h:"ていか", m:"a fixed price"},
      {k:"合格", h:"ごうかく", m:"to pass an exam"},
      {k:"格安", h:"かくやす", m:"a bargain"},
      {k:"申し込む", h:"もうしこむ", m:"to apply"},
      {k:"申告", h:"しんこく", m:"a declaration"},
      {k:"申す", h:"もうす", m:"to say (humble form)"},
      {k:"申込書", h:"もうしこみしょ", m:"an application form"},
    ]},
  { id:"w4d4", week:4, day:4, route:"w4/d4", jp:"四日目", en:"Day 4", glyph:"日",
    words:[
      {k:"申請", h:"しんせい", m:"application"},
      {k:"申し上げる", h:"もうしあげる", m:"to say (very humble form)"},
      {k:"記入", h:"きにゅう", m:"entry"},
      {k:"記号", h:"きごう", m:"a sign, a symbol"},
      {k:"日記", h:"にっき", m:"a diary, journal"},
      {k:"記事", h:"きじ", m:"an article"},
      {k:"年齢", h:"ねんれい", m:"age"},
      {k:"高齢", h:"こうれい", m:"old age"},
      {k:"〜歳", h:"〜さい", m:"~years old"},
      {k:"二十歳", h:"にじゅっさい", m:"20 years old"},
      {k:"二十歳", h:"はたち", m:"20 years old"},
      {k:"性別", h:"せいべつ", m:"sex/gender"},
      {k:"女性", h:"じょせい", m:"woman"},
      {k:"性格", h:"せいかく", m:"personality"},
      {k:"男性", h:"だんせい", m:"man"},
      {k:"連休", h:"れんきゅう", m:"a holiday"},
      {k:"連れて行く", h:"つれていく", m:"to take someone to...."},
      {k:"連れて来る", h:"つれてくる", m:"to bring someone to..."},
      {k:"連絡", h:"れんらく", m:"contact, connection"},
      {k:"届ける", h:"とどける", m:"to deliver"},
      {k:"届く", h:"とどく", m:"to arrive (mail)"},
    ]},
  { id:"w4d5", week:4, day:5, route:"w4/d5", jp:"五日目", en:"Day 5", glyph:"日",
    words:[
      {k:"自宅", h:"じたく", m:"one's house/home"},
      {k:"宅配", h:"たくはい", m:"a delivery to someone's house"},
      {k:"お宅", h:"おたく", m:"house/home (respectful form)"},
      {k:"配達", h:"はいたつ", m:"a delivery"},
      {k:"心配", h:"しんぱい", m:"anxiety/worry"},
      {k:"配送料", h:"はいそうりょう", m:"a shipping charge"},
      {k:"配る", h:"くばる", m:"to distribute"},
      {k:"希望", h:"きぼう", m:"hope"},
      {k:"失望", h:"しつぼう", m:"despair"},
      {k:"望む", h:"のぞむ", m:"to want, to hope for"},
      {k:"入荷", h:"にゅうか", m:"a receipt (of goods)"},
      {k:"荷物", h:"にもつ", m:"luggage"},
      {k:"出荷", h:"しゅっか", m:"shipment"},
      {k:"手荷物", h:"てにもつ", m:"hand luggage"},
      {k:"交換", h:"こうかん", m:"exchange"},
      {k:"乗り換え", h:"のりかえ", m:"changing trains"},
      {k:"代金引換", h:"だいきんひきかえ", m:"cash on delivery"},
      {k:"代引き", h:"だいびき", m:"cash on delivery"},
      {k:"金額", h:"きんがく", m:"an amount/sum (of money)"},
      {k:"半額", h:"はんがく", m:"half price"},
      {k:"不在", h:"ふざい", m:"absence"},
    ]},
  { id:"w4d6", week:4, day:6, route:"w4/d6", jp:"六日目", en:"Day 6", glyph:"日",
    words:[
      {k:"現在", h:"げんざい", m:"present (time)"},
      {k:"取る", h:"とる", m:"to take"},
      {k:"受け取る", h:"うけとる", m:"to receive, to take"},
      {k:"受取人", h:"うけとりにん", m:"a recipient"},
      {k:"預金", h:"よきん", m:"a money deposit"},
      {k:"預ける", h:"あずける", m:"to entrust"},
      {k:"衣類", h:"いるい", m:"clothing"},
      {k:"衣服", h:"いふく", m:"clothes"},
      {k:"参加", h:"さんか", m:"participation"},
      {k:"参る", h:"まいる", m:"to go/come (humble form)"},
      {k:"参考書", h:"さんこうしょ", m:"a reference book"},
      {k:"上達", h:"じょうたつ", m:"making progress, improvement"},
      {k:"友達", h:"ともだち", m:"a friend"},
      {k:"速達", h:"そくたつ", m:"a special delivery"},
      {k:"通勤", h:"つうきん", m:"commuting to work"},
      {k:"勤める", h:"つとめる", m:"to work, to be employed"},
      {k:"携帯電話", h:"けいたいでんわ", m:"a cellphone, a mobile phone"},
      {k:"帯", h:"おび", m:"a belt/sash"},
      {k:"時間帯", h:"じかんたい", m:"a time zone, a time slot"},
      {k:"細い", h:"ほそい", m:"fine, thin"},
      {k:"細かい", h:"こまかい", m:"fine/small"},
    ]},
  { id:"w4d7", week:4, day:7, route:"w4/d7", jp:"七日目", en:"Day 7", glyph:"日",
    words:[
      {k:"戸", h:"と", m:"a door"},
      {k:"戸棚", h:"とだな", m:"a closet, a cupboard"},
      {k:"雨戸", h:"あまど", m:"a sliding storm door"},
      {k:"びわ湖", h:"びわこ", m:"Lake Biwa"},
      {k:"湖", h:"みずうみ", m:"a lake"},
      {k:"風船", h:"ふうせん", m:"balloon"},
      {k:"船", h:"ふね", m:"a boat, ship"},
      {k:"船長", h:"せんちょう", m:"a captain"},
      {k:"船便", h:"ふなびん", m:"surface, sea-mail"},
      {k:"角度", h:"かくど", m:"an angle"},
      {k:"四角い", h:"しかくい", m:"square"},
      {k:"三角形", h:"さんかくけい", m:"a triangle"},
      {k:"角", h:"かど", m:"a corner"},
      {k:"夫妻", h:"ふさい", m:"husband and wife"},
      {k:"夫婦", h:"ふうふ", m:"a married couple"},
      {k:"夫", h:"おっと", m:"a husband"},
      {k:"苦労", h:"くろう", m:"troubles, hardships"},
      {k:"苦い", h:"にがい", m:"bitter"},
      {k:"苦しい", h:"くるしい", m:"distressful, trying"},
      {k:"苦手（な）", h:"にがて（な）", m:"a weak point"},
    ]},
  { id:"w5d1", week:5, day:1, route:"w5/d1", jp:"一日目", en:"Day 1", glyph:"日",
    words:[
      {k:"お礼", h:"おれい", m:"thanks"},
      {k:"伺う", h:"うかがう", m:"to visit, to ask (humble form)"},
      {k:"遅刻", h:"ちこく", m:"tardiness"},
      {k:"遅い", h:"おそい", m:"slow"},
      {k:"遅れる", h:"おくれる", m:"to be late"},
      {k:"失礼（な）", h:"しつれい（な）", m:"rudeness"},
      {k:"失敗", h:"しっぱい", m:"failure, mistake"},
      {k:"失礼する", h:"しつれいする", m:"to be excused"},
      {k:"汗", h:"あせ", m:"perspiration, sweat"},
      {k:"汗をかく", h:"あせをかく", m:"to sweat"},
      {k:"残念（な）", h:"ざんねん（な）", m:"regret, disappointment"},
      {k:"記念", h:"きねん", m:"commemoration"},
      {k:"涙", h:"なみだ", m:"tears"},
      {k:"涙を流す", h:"なみだをながす", m:"to weep"},
      {k:"笑う", h:"わらう", m:"to laugh, to smile"},
      {k:"笑顔", h:"えがお", m:"smiling face"},
      {k:"笑い", h:"わらい", m:"laughter, smile"},
      {k:"調子", h:"ちょうし", m:"condition"},
      {k:"調べる", h:"しらべる", m:"to look up something, to investigate"},
      {k:"強調", h:"きょうちょう", m:"emphasis, stress"},
      {k:"調査", h:"ちょうさ", m:"an investigation, inquiry"},
    ]},
  { id:"w5d2", week:5, day:2, route:"w5/d2", jp:"二日目", en:"Day 2", glyph:"日",
    words:[
      {k:"移動", h:"いどう", m:"movement, transfer"},
      {k:"移る", h:"うつる", m:"to move, to shift"},
      {k:"移す", h:"うつす", m:"to move/shift (something)"},
      {k:"困難（な）", h:"こんなん（な）", m:"difficult"},
      {k:"難しい", h:"むずかしい", m:"difficult"},
      {k:"難問", h:"なんもん", m:"a difficult problem"},
      {k:"簡単（な）", h:"かんたん（な）", m:"easy"},
      {k:"単個", h:"たんご", m:"vocabulary"},
      {k:"単位", h:"たんい", m:"a unit, credit"},
      {k:"感じる", h:"かんじる", m:"to feel"},
      {k:"感動", h:"かんどう", m:"inspiration"},
      {k:"感想", h:"かんそう", m:"impressions, thoughts"},
      {k:"予想", h:"よそう", m:"anticipation, forecast"},
      {k:"練習", h:"れんしゅう", m:"practice"},
      {k:"最近", h:"さいきん", m:"recently"},
      {k:"最後", h:"さいご", m:"last, end"},
      {k:"最初", h:"さいしょ", m:"first, beginning"},
      {k:"最も", h:"もっとも", m:"most"},
      {k:"適当（な）", h:"てきとう（な）", m:"correct, appropriate"},
      {k:"快適（な）", h:"かいてき（な）", m:"comfortable"},
    ]},
  { id:"w5d3", week:5, day:3, route:"w5/d3", jp:"三日目", en:"Day 3", glyph:"日",
    words:[
      {k:"選挙", h:"せんきょ", m:"an election"},
      {k:"選ぶ", h:"えらぶ", m:"to choose"},
      {k:"選手", h:"せんしゅ", m:"a player, an athlete"},
      {k:"違う", h:"ちがう", m:"different, wrong"},
      {k:"間違い", h:"まちがい", m:"a mistake"},
      {k:"間違う", h:"まちがう", m:"to make a mistake"},
      {k:"間違える", h:"まちがえる", m:"to make a mistake"},
      {k:"直線", h:"ちょくせん", m:"a straight line"},
      {k:"直る", h:"なおる", m:"to be repaired"},
      {k:"直接", h:"ちょくせつ", m:"direct"},
      {k:"直す", h:"なおす", m:"to fix"},
      {k:"復習", h:"ふくしゅう", m:"review, revision"},
      {k:"回復", h:"かいふく", m:"recovery, recuperation"},
      {k:"往復", h:"おうふく", m:"a round trip"},
      {k:"辞書", h:"じしょ", m:"a dictionary"},
      {k:"辞める", h:"やめる", m:"to resign, to retire"},
      {k:"宿題", h:"しゅくだい", m:"a homework"},
      {k:"宿", h:"やど", m:"an inn, a hotel"},
      {k:"下宿", h:"げしゅく", m:"lodgings"},
      {k:"昨日", h:"さくじつ；きのう", m:"yesterday"},
    ]},
  { id:"w5d4", week:5, day:4, route:"w5/d4", jp:"四日目", en:"Day 4", glyph:"日",
    words:[
      {k:"昨夜", h:"さくや", m:"last night"},
      {k:"昨年", h:"さくねん", m:"last year"},
      {k:"〜君", h:"〜くん", m:"honorific to name of males younger than oneself"},
      {k:"君", h:"きみ", m:"you"},
      {k:"結構（な）", h:"けっこう（な）", m:"splendid, nice"},
      {k:"結局", h:"けっきょく", m:"after all"},
      {k:"いいえ、結構です", h:"いいえ、けっこうです", m:"no, thank you"},
      {k:"結ぶ", h:"むすぶ", m:"to tie, to connect, to conclude"},
      {k:"結婚", h:"けっこん", m:"a marriage"},
      {k:"婚約", h:"こんやく", m:"an engagement"},
      {k:"新婚旅行", h:"しんこんりょこう", m:"a honeymoon"},
      {k:"祝日", h:"しゅくじつ", m:"a holiday, a festival day"},
      {k:"祝う", h:"いわう", m:"to celebrate, to congratulate"},
      {k:"お祝い", h:"おいわい", m:"celebration, congratulation"},
      {k:"曲", h:"きょく", m:"a piece of music"},
      {k:"曲がる", h:"まがる", m:"to bend, to turn a corner"},
      {k:"曲線", h:"きょくせん", m:"a curve"},
      {k:"曲げる", h:"まげる", m:"to bend"},
      {k:"奥さん", h:"おくさん", m:"another person's wife"},
      {k:"奥", h:"おく", m:"inmost"},
    ]},
  { id:"w5d5", week:5, day:5, route:"w5/d5", jp:"五日目", en:"Day 5", glyph:"日",
    words:[
      {k:"寝る", h:"ねる", m:"to sleep"},
      {k:"昼寝", h:"ひるね", m:"a nap"},
      {k:"寝坊", h:"ねぼう", m:"late riser, sleepyhead"},
      {k:"頭痛", h:"ずつう", m:"a headache"},
      {k:"痛い", h:"いたい", m:"sore, painful"},
      {k:"腹痛", h:"ふくつう", m:"stomach ache"},
      {k:"熱", h:"ねつ", m:"heat, fever"},
      {k:"熱い", h:"あつい", m:"hot"},
      {k:"熱心（な）", h:"ねっしん（な）", m:"enthusiasm, zeal"},
      {k:"虫", h:"むし", m:"an insect"},
      {k:"歯科", h:"しか", m:"dentistry"},
      {k:"歯医者", h:"はいしゃ", m:"a dentist"},
      {k:"歯", h:"は", m:"teeth"},
      {k:"虫歯", h:"むしば", m:"a decayed tooth"},
      {k:"政治", h:"せいじ", m:"politics, government"},
      {k:"治る", h:"なおる", m:"to heal"},
      {k:"治療", h:"ちりょう", m:"a treatment"},
      {k:"治す", h:"なおす", m:"to cure"},
      {k:"汚い", h:"きたない", m:"dirty"},
      {k:"汚れる", h:"よごれる", m:"to become dirty"},
    ]},
  { id:"w5d6", week:5, day:6, route:"w5/d6", jp:"六日目", en:"Day 6", glyph:"日",
    words:[
      {k:"並ぶ", h:"ならぶ", m:"to stand in a line"},
      {k:"歯並び", h:"はならび", m:"the allignment of your teeth"},
      {k:"並べる", h:"ならべる", m:"to line up, to set up"},
      {k:"他の", h:"たの", m:"other"},
      {k:"その他", h:"そのた", m:"other"},
      {k:"身長", h:"しんちょう", m:"height"},
      {k:"身分", h:"みぶん", m:"social status"},
      {k:"独身", h:"どくしん", m:"single, unmarried"},
      {k:"刺身", h:"さしみ", m:"sashimi (sliced raw fish)"},
      {k:"日本酒", h:"にほんしゅ", m:"sake"},
      {k:"お酒", h:"おさけ", m:"alcohol, liquor"},
      {k:"料理酒", h:"りょうりしゅ", m:"cooking sake"},
      {k:"酒屋", h:"さかや", m:"a liquor store"},
      {k:"呼吸", h:"こきゅう", m:"breathing, respiration"},
      {k:"吸う", h:"すう", m:"to breathe, to inhale, to smoke"},
      {k:"食欲", h:"しょくよく", m:"appetite"},
      {k:"欲しい", h:"ほしい", m:"want"},
      {k:"意欲", h:"いよく", m:"a will, eagerness, motivation"},
      {k:"睡眠", h:"すいみん", m:"sleep"},
      {k:"眠い", h:"ねむい", m:"sleepy"},
    ]},
  { id:"w5d7", week:5, day:7, route:"w5/d7", jp:"七日目", en:"Day 7", glyph:"日",
    words:[
      {k:"眠る", h:"ねむる", m:"to sleep"},
      {k:"疲れる", h:"つかれる", m:"to get tired, to be exhausted"},
      {k:"息", h:"いき", m:"a breath"},
      {k:"息子", h:"むすこ", m:"a son"},
      {k:"息切れ", h:"いきぎれ", m:"be short of breath"},
      {k:"呼ぶ", h:"よぶ", m:"to call"},
      {k:"厚い", h:"あつい", m:"thick"},
      {k:"泣く", h:"なく", m:"to cry, to weep"},
      {k:"鳴く", h:"なく", m:"to chirtp, to croak/ bleat"},
      {k:"鳴る", h:"なる", m:"to ring, to chime"},
      {k:"最初", h:"さいしょ", m:"first, beginning"},
      {k:"初め", h:"はじめ", m:"the beginning"},
      {k:"初級", h:"しょきゅう", m:"beginning level"},
      {k:"初めて", h:"はじめて", m:"first time"},
      {k:"宿泊", h:"しゅくはく", m:"lodging"},
      {k:"泊まる", h:"とまる", m:"to stay"},
      {k:"泊める", h:"とめる", m:"to put a person up, to let someone stay"},
      {k:"紅葉", h:"こうよう", m:"autumn leaves"},
      {k:"葉", h:"は", m:"a leaf"},
      {k:"言葉", h:"ことば", m:"word, language"},
    ]},
  { id:"w6d1", week:6, day:1, route:"w6/d1", jp:"一日目", en:"Day 1", glyph:"日",
    words:[
      {k:"予報", h:"よほう", m:"a forecast"},
      {k:"報告", h:"ほうこく", m:"a report"},
      {k:"晴れる", h:"はれる", m:"to be sunny"},
      {k:"晴れ", h:"はれ", m:"fine weather"},
      {k:"雲", h:"くも", m:"clouds"},
      {k:"吹く", h:"ふく", m:"to blow"},
      {k:"暖房", h:"だんぼう", m:"a heater"},
      {k:"暖かい", h:"あたたかい", m:"warm"},
      {k:"雪", h:"ゆき", m:"snow"},
      {k:"地震", h:"じしん", m:"an earthquake"},
      {k:"震度", h:"しんど", m:"seismic intensity"},
      {k:"電波", h:"でんぱ", m:"electromagnetic wave"},
      {k:"波", h:"なみ", m:"a wave"},
      {k:"津波", h:"つなみ", m:"tsunami"},
      {k:"要求", h:"ようきゅう", m:"a demand, request"},
      {k:"請求書", h:"せいきゅうしょ", m:"a bill, invoice"},
      {k:"求人", h:"きゅうじん", m:"'Help wanted'"},
      {k:"求める", h:"もとめる", m:"to demand, to request"},
    ]},
  { id:"w6d2", week:6, day:2, route:"w6/d2", jp:"二日目", en:"Day 2", glyph:"日",
    words:[
      {k:"募集", h:"ぼしゅう", m:"recruiment"},
      {k:"職場", h:"しょくば", m:"a work place"},
      {k:"転職", h:"てんしょく", m:"change of job, a job-change"},
      {k:"職業", h:"しょくぎょう", m:"an occupation, profession"},
      {k:"職員", h:"しょくいん", m:"employees"},
      {k:"美容院", h:"びよういん", m:"a hairdresser"},
      {k:"内容", h:"ないよう", m:"contents/ substance"},
      {k:"技術", h:"ぎじゅつ", m:"technique, technology"},
      {k:"技術者", h:"ぎじゅつしゃ", m:"a technician"},
      {k:"一般", h:"いっぱん", m:"general, average"},
      {k:"一般に", h:"いっぱんに", m:"in general"},
      {k:"事務", h:"じむ", m:"office work"},
      {k:"事務所", h:"じむしょ", m:"an office"},
      {k:"公務員", h:"こうむいん", m:"a civil servant, government employee"},
      {k:"税務署", h:"ぜいむしょ", m:"tax office"},
      {k:"第１課", h:"だい１か", m:"Lesson one"},
      {k:"課長", h:"かちょう", m:"a section chief"},
      {k:"地球", h:"ちきゅう", m:"earth"},
      {k:"電球", h:"でんきゅう", m:"a light bulb"},
    ]},
  { id:"w6d3", week:6, day:3, route:"w6/d3", jp:"三日目", en:"Day 3", glyph:"日",
    words:[
      {k:"野球", h:"やきゅう", m:"baseball"},
      {k:"決して", h:"けっして", m:"by no means"},
      {k:"決める", h:"きめる", m:"to decide (something)"},
      {k:"決定", h:"けってい", m:"a decision"},
      {k:"決まる", h:"きまる", m:"to be decided"},
      {k:"優勝", h:"ゆうしょう", m:"a victory, championship"},
      {k:"勝つ", h:"かつ", m:"to win"},
      {k:"決勝", h:"けっしょう", m:"final game"},
      {k:"１対２", h:"１たい２", m:"(a score of) one to two"},
      {k:"反対", h:"はんたい", m:"opposite"},
      {k:"流れる", h:"ながれる", m:"to flow"},
      {k:"流す", h:"ながす", m:"to let (water, etc) flow"},
      {k:"勝負", h:"しょうぶ", m:"a match, contest, game"},
      {k:"負ける", h:"まける", m:"to lose"},
      {k:"投手", h:"とうしゅ", m:"(baseball) pitcher"},
      {k:"投げる", h:"なげる", m:"to throw"},
      {k:"結果", h:"けっか", m:"a result"},
      {k:"果物", h:"くだもの", m:"fruit"},
      {k:"戦後", h:"せんご", m:"after the war"},
    ]},
  { id:"w6d4", week:6, day:4, route:"w6/d4", jp:"四日目", en:"Day 4", glyph:"日",
    words:[
      {k:"戦う", h:"たたかう", m:"to fight"},
      {k:"戦争", h:"せんそう", m:"war"},
      {k:"経験", h:"けいけん", m:"an experience"},
      {k:"経営", h:"けいえい", m:"management"},
      {k:"経済", h:"けいざい", m:"economy"},
      {k:"済む", h:"すむ", m:"to finish"},
      {k:"成長", h:"せいちょう", m:"growth"},
      {k:"完成", h:"かんせい", m:"completion"},
      {k:"貿易", h:"ぼうえき", m:"trade"},
      {k:"易しい", h:"やさしい", m:"easy, plain, simple"},
      {k:"輸出", h:"ゆしゅつ", m:"export"},
      {k:"輸送", h:"ゆそう", m:"transport, transportation"},
      {k:"輸入", h:"ゆにゅう", m:"import"},
      {k:"相談", h:"そうだん", m:"consultation"},
      {k:"相手", h:"あいて", m:"an opponent/competitor"},
      {k:"首相", h:"しゅしょう", m:"prime minister"},
      {k:"文化", h:"ぶんか", m:"culture"},
      {k:"化学", h:"かがく", m:"chemistry"},
    ]},
  { id:"w6d5", week:6, day:5, route:"w6/d5", jp:"五日目", en:"Day 5", glyph:"日",
    words:[
      {k:"〜化", h:"〜か", m:"~ize (change something into something else)"},
      {k:"化粧", h:"けしょう", m:"makeup, cosmetics"},
      {k:"比べる", h:"くらべる", m:"to compare"},
      {k:"原料", h:"げんりょう", m:"raw materials"},
      {k:"原因", h:"げんいん", m:"a cause"},
      {k:"国際（の）", h:"こくさい（の）", m:"international"},
      {k:"交際", h:"こうさい", m:"association/dealings (with)"},
      {k:"会議", h:"かいぎ", m:"a meeting"},
      {k:"議員", h:"ぎいん", m:"a member of an assembly"},
      {k:"生活", h:"せいかつ", m:"life, livelihood"},
      {k:"活動", h:"かつどう", m:"activity"},
      {k:"大変（な）", h:"たいへん（な）", m:"very serious"},
      {k:"変わる", h:"かわる", m:"change"},
      {k:"変化", h:"へんか", m:"a change"},
      {k:"変える", h:"かえる", m:"to change (something)"},
      {k:"政治", h:"せいじ", m:"politics"},
      {k:"政治家", h:"せいじか", m:"a politician"},
      {k:"政府", h:"せいふ", m:"government, administration"},
    ]},
  { id:"w6d6", week:6, day:6, route:"w6/d6", jp:"六日目", en:"Day 6", glyph:"日",
    words:[
      {k:"都道府県", h:"とどうふけん", m:"prefectures"},
      {k:"改正", h:"かいせい", m:"an amendment"},
      {k:"改める", h:"あらためる", m:"to change, to check"},
      {k:"改札口", h:"かいさつぐち", m:"a ticket gate"},
      {k:"否定", h:"ひてい", m:"negation"},
      {k:"否定的（な）", h:"ひていてき（な）", m:"negative"},
      {k:"国際的（な）", h:"こくさいてき（な）", m:"international"},
      {k:"目的", h:"もくてき", m:"an aim, purpose"},
      {k:"個人的（な）", h:"こじんてき（な）", m:"personal"},
      {k:"実際に", h:"じっさいに", m:"practice, actual conditions"},
      {k:"実験", h:"じっけん", m:"an experiment"},
      {k:"実は", h:"じつは", m:"to tell the truth"},
      {k:"欠点", h:"けってん", m:"a shortcoming"},
      {k:"欠ける", h:"かける", m:"to lack"},
      {k:"欠席", h:"けっせき", m:"absence"},
      {k:"専門", h:"せんもん", m:"specialty"},
      {k:"専門家", h:"せんもんか", m:"an expert"},
      {k:"死亡", h:"しぼう", m:"death"},
    ]},
  { id:"w6d7", week:6, day:7, route:"w6/d7", jp:"七日目", en:"Day 7", glyph:"日",
    words:[
      {k:"亡くなる", h:"なくなる", m:"to die"},
      {k:"多忙（な）", h:"たぼう（な）", m:"busy"},
      {k:"忙しい", h:"いそがしい", m:"busy"},
      {k:"忘年会", h:"ぼうねんかい", m:"end of year party"},
      {k:"忘れる", h:"わすれる", m:"to forget"},
      {k:"忘れ物", h:"わすれもの", m:"thing left behind (lost property)"},
      {k:"文化祭", h:"ぶんかさい", m:"a school festival"},
      {k:"（お）祭り", h:"（お）まつり", m:"a festival"},
      {k:"苦労", h:"くろう", m:"troubles, hardships"},
      {k:"労働者", h:"ろうどうしゃ", m:"a labourer"},
      {k:"参加", h:"さんか", m:"participation"},
      {k:"加える", h:"くわえる", m:"to add to"},
      {k:"増加", h:"ぞうか", m:"increase"},
      {k:"情報", h:"じょうほう", m:"information"},
      {k:"事情", h:"じじょう", m:"circumstance"},
      {k:"表情", h:"ひょうじょう", m:"a facial expression"},
      {k:"感情", h:"かんじょう", m:"emotions"},
      {k:"反対", h:"はんたい", m:"opposite"},
    ]},
];

/* Weeks are derived from CATEGORIES so they stay correct after the app
   reloads word lists out of the local SQL database. */
const WEEKS = [1,2,3,4,5,6].map(n => ({
  id:`w${n}`,
  n,
  jp:`第${WEEK_NUMERALS[n-1]}週`,
  en:`Week ${n}`,
  glyph:"週",
  get days(){ return CATEGORIES.filter(c => c.week === n); },
  get wordCount(){ return this.days.reduce((sum, d) => sum + d.words.length, 0); },
}));

const byId = id => CATEGORIES.find(c => c.id === id);
const weekById = id => WEEKS.find(w => w.id === id);
